CUber alarms
CooperUnion/selfdrive pull request #111
Opened 2023-02-05 07:08 UTC by jacobkoziej

In light of our supervisor daemon, we'll need nodes to signal what kinds of errors they're experiencing.

Each node (if applicable) will have a bit-field with possible alarms. If another node wishes to subscribe to the current node's alarms, they can quickly check for current errors by checking if the bit-field is `!= 0`, or if any alarms have changed since their last check by performing a XOR against the inverse of the previously checked bit-mask.

2023-02-05 07:09 UTC, dmezh commented
Doesn't it make more sense to just split them out into individual signals

2023-02-05 08:07 UTC, jacobkoziej commented
> Doesn't it make more sense to just split them out into individual signals

My reasoning against it is because of the overhead. At the moment OpenCAN doesn't have support for flags. You can imagine having a full message of 1-bit alarms and then having to not only decode each alarm, but then call a function to check each individual alarm instead of all of them in parallel.

2023-02-05 15:41 UTC, ajaku approved these changes, later dismissed

2023-02-05 15:41 UTC, dmezh commented
> > Doesn't it make more sense to just split them out into individual signals
> 
> My reasoning against it is because of the overhead. At the moment OpenCAN doesn't have support for flags. You can imagine having a full message of 1-bit alarms and then having to not only decode each alarm, but then call a function to check each individual alarm instead of all of them in parallel.

I think the unpack code boils down to a single bitwise-and per flag, so basically what you'd be doing by checking it manually anyway. I would make a 1-bit signal for each flag and then you can also make a signal that indicates if any of them at all are raised.

2023-02-05 15:54 UTC, dmezh commented
+ without them being actually broken out on CAN, you won't be able to easily see them on traces, nor use them from Python without additional work.

2023-02-05 19:51 UTC, dmezh requested changes
Marking request changes for now

2023-02-07 18:25 UTC, jacobkoziej commented
> > > Doesn't it make more sense to just split them out into individual signals
> > 
> > 
> > My reasoning against it is because of the overhead. At the moment OpenCAN doesn't have support for flags. You can imagine having a full message of 1-bit alarms and then having to not only decode each alarm, but then call a function to check each individual alarm instead of all of them in parallel.
> 
> I think the unpack code boils down to a single bitwise-and per flag, so basically what you'd be doing by checking it manually anyway. I would make a 1-bit signal for each flag and then you can also make a signal that indicates if any of them at all are raised.

Ah didn't even think of that, great idea!

2023-02-07 19:13 UTC, dmezh approved these changes, later dismissed
Approving but would prefer the name change. This should be good for us! I think we could make a library to more generally handle this in the future. I am thinking of adding a distributed TX mode to OpenCAN where you update signals individually and asynchronously using function calls rather than providing them in a populate function. That would improve the ergonomics, although the `alarmsRaised` signal might be more complicated.

2023-02-07 19:13 UTC, dmezh commented on can/can.yml
> +          - alarmSpeed:
Nit: I think `speedAlarm` reads better here

2023-02-07 20:57 UTC, dmezh approved these changes
Looks good. Let's think about latching logic later.

2023-02-07 21:13 UTC, merged