User/giuseppequaratino/2 15 test day
CooperUnion/selfdrive pull request #120
Opened 2023-02-15 23:13 UTC by giuseppequaratino

Merge in encoder_odom and techbus ros nodes into dev. Also remove some unused ros packages in an effort to start cleaning the tech stack

2023-02-17 20:00 UTC, giuseppequaratino commented on can/can.yml
> +        # GO INTO DBC search for angleCmd and change @1+ to @1- for signed values
outdated comment

2023-02-17 20:01 UTC, giuseppequaratino commented on can/can.yml
> +
unused message meant for testing

2023-02-17 20:11 UTC, giuseppequaratino commented on ros/docker/encoder_odom/src/encoder_arduino.py
> +#!/usr/bin/env python3
This file hasn't been used for testing yet. Needs to incorporate the changes from encoder_odom.py as well so probably shouldn't merge it.

2023-03-09 21:09 UTC, dmezh requested changes

2023-03-09 21:09 UTC, dmezh commented on .editorconfig
> -# Cooper IGVC EditorConfig
Why deleted?

2023-03-09 21:09 UTC, dmezh commented on Makefile
> +	cargo install --root build/cargo --locked --git https://github.com/opencan/opencan --rev f90d5c42
- [ ] Change version to non-hack before merge

2023-03-09 21:09 UTC, dmezh commented on ctrl/velocity-controller/ctrl.py
> +        self.throttle_percent = 0
Should these also start off as floats?

2023-03-09 21:09 UTC, dmezh commented on ctrl/velocity-controller/vel.py
> +    ACCEL_TO_PEDAL_SLOPE_MAPPING        = 15.4
imo these names could be more clear; it's not apparent what `X_TO_SLOPE_MAPPING` means

2023-03-09 21:09 UTC, dmezh commented on dbw/py-steering/base.py
> +#        self._sys_state = 'ESTOP'
Is this staying or going?

2023-03-09 21:09 UTC, dmezh commented on dbw/py-steering/steer.py
> -                    'STEER_angle':             math.radians(self._cur_angle),
Change this back once we get signed support merged?

2023-03-09 21:09 UTC, dmezh commented on ros/docker-compose.yml
> +            - 'ROS_HOSTNAME=pure_pursuit'
:)

2023-03-09 21:09 UTC, dmezh commented on ros/docker-compose.yml
> +        build: docker/techbus/.
```suggestion
        build: docker/techbus/
```

2023-03-09 21:09 UTC, dmezh commented on ros/docker/encoder_odom/Dockerfile
> +RUN apt-get install -y python3-tf-conversions
Docker caches in between these RUN directives, meaning the `apt-get update` line could be cached and then the `apt-get install` line runs on a cached version of the apt lists. You need to run update in the same RUN directive:

```suggestion
RUN apt-get update && apt-get install -yq python3-tf2-ros python3-tf-conversions
```

2023-03-09 21:09 UTC, dmezh commented on ros/docker/encoder_odom/src/encoder_odom.py
> +
order imports

2023-03-09 21:09 UTC, dmezh commented on ros/docker/encoder_odom/src/encoder_odom.py
> +        #starting the node at 0 ticks might cause a problem with absolute encoders???
yes, you should wait to publish encoder data until you see the first tick and set the initial values to it.

2023-03-09 21:09 UTC, dmezh commented on ros/docker/encoder_odom/src/encoder_odom.py
> +        tick_distance = circumfrence/enc_res
```suggestion
        tick_distance = circumference/enc_res
```

2023-03-09 21:09 UTC, dmezh commented on ros/docker/encoder_odom/src/encoder_odom.py
> +        pub.publish("hello")
remove?

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/global_ros_pp.py
> +    except NoIntersectionException as e:
An exception is thrown and then immediately caught, so is there a point? In other words, what do you actually want to do when we have no intersection?

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/global_ros_pp.py
> +    dist_x = abs(a*lookahead_x + lookahead_y + c)/math.sqrt(((a)**2)+1)
Please make spacing more consistent

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/global_ros_pp.py
> +        publisher.publish(ppc_cmd)
Missing newline at end of file

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/path_gen.py
> +        rate.sleep()
Missing newline at end of file

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/ppwork.py
> +import math
Which one of the pure pursuit controller files is correct?

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/path_gen.py
> +#!/usr/bin/env python3
Maybe a different name for this file would be good - `path_test_gen.py`?

2023-03-09 21:09 UTC, dmezh commented on ros/docker/pure_pursuit/src/ros_pp.py
> +#!/usr/bin/env python3
A third pure pursuit controller file - which one is right?

2023-03-09 21:09 UTC, dmezh commented on ros/docker/techbus/Dockerfile
> +
```suggestion
```

2023-03-09 21:09 UTC, dmezh commented on ros/docker/techbus/Dockerfile
> +
```suggestion

# install redis
```

2023-03-09 21:09 UTC, dmezh commented on ros/docker/techbus/src/techbus.py
> +            rospy.loginfo(f"Warning: invalid steering angle combo:lin.x:{msg.linear.x}, ang.z:{msg.angular.z}")
```suggestion
            rospy.loginfo(f"Warning: invalid steering angle/linear velocity combo: lin.x:{msg.linear.x}, ang.z:{msg.angular.z}")
```

2023-03-09 21:09 UTC, dmezh commented on ros/docker/techbus/src/techbus.py
> +            'STEER_angleCmd': angle
We should make the message `DBW_steeringAngleCmd`

2023-03-09 21:09 UTC, dmezh commented on ros/docker/techbus/src/techbus.py
> +# redis local host flag on cand --redis_host localhost
Missing newline at end of file

2023-03-09 21:09 UTC, dmezh commented on ros/test-scripts/calibrate-start.sh
> +tmux send-keys Enter
Missing newline at end of file

2023-03-09 21:09 UTC, dmezh commented on ros/test-scripts/cand-start.sh
> +tmux send-keys Enter
Missing newline at end of file

2023-03-09 21:09 UTC, dmezh commented on startup.sh
> +
Maybe leave a comment explaining the script

2023-03-09 21:10 UTC, dmezh commented
Merging this will be huge! Exciting work 😄

2023-03-26 20:32 UTC, dmezh commented
What's the status on this?

2023-03-27 23:18 UTC, dmezh requested changes
Please address the outstanding comments.

2023-04-01 21:14 UTC, dmezh approved these changes
Approving on condition that outstanding comments get resolved later over time.

2023-04-02 20:55 UTC, merged