User/vaibhav hariani/lane following merge
CooperUnion/selfdrive pull request #185
Opened 2024-05-17 18:16 UTC by Vaibhav-Hariani

Adding most of lane following here: This is the first merge request that should be accepted. Once this is accepted, the other two (UI, which involves changes to these files as well), should be accepted. 

Following that, Object detection should be merged. That is not complete.

2024-05-19 01:49 UTC, jacobkoziej requested changes
This branch is not at all in a state for merging.

First and foremost, please branch off of `dev` and add back in the lane following code with atomic commits so that it's clear what's happening. If you did not write a code segments and are merely refactoring, please co-commit to give credit where credit is due.

There is still code that is not our own in this branch. The Apache 2.0 license is compatible with the GPLv3, but this is still unacceptable to do. This code must be removed.

The directory structure also does not make sense. The `ros2/` directory seems to be structured like this is meant to be one big ROS 2 package, but then the `ros2/UI` is thrown in there confusing me. Please move this into an appropriate `component/` directory as per the repo layout: https://cooperunion.github.io/selfdrive/getting-started.html#repo-layout

There are also just general Python programming things that are not respected which should be respected going forth:
- Do not hard-code paths
- No magic numbers
- Follow PEP 8
- Remove commented out code that serves no purpose
- Have descriptive names (these should be descriptive so `object_distance` over `obj_dist`)
- Please read the general api's for numpy and and opencv so that you're not duplicating existing functionality
- Use `@property` if you plan to have getters/setters in your classes
- Do not use global variables. There is almost never _any_ good justification in such a high-level language.

Last thing, binary files should be included with Git LFS. This is the main reason for why I want fresh history as now you will force every clone of the repo to pull multiple `mp4` files even though they're not gonna be in the main source tree. If you used Git LFS, this would be more acceptable as only the binary files in the source tree would be pulled in an initial clone.

2024-05-19 01:49 UTC, jacobkoziej commented on .gitignore
> +ros2/lanefollowingtest/LaneVideo.mp4
Why is this video file getting added? Why isn't it tracked with Git LFS?

2024-05-19 01:49 UTC, jacobkoziej commented on .gitignore
> +ros2/log/latest_build
The top level `.gitignore` is only for files in the root of the directory, or patterns that should be respected throughout the repo. Please make a `.gitignore` specific to the lane following node or in the `ros2/` directory if you believe these patterns will be common in ROS 2.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/UI/ 🚗 Homepage.py
This file should not be here. Why the snarky comments to the first year students?

Most of the file looks like a TODO list.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/test_lf.py
Why isn't this test in the same directory as the rest of the lane follower?

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +vidcap_left = cv2.VideoCapture("/dev/video0")
This should not be a hard-coded path. This should be a parameter that's passed into the file.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +matrix = cv2.getPerspectiveTransform(pts1, pts2)
You made classes for the individual components of the lane line following code, but then sprinkled these random global variables around. If these variables are passed to the UI, they should be encapsulated in a class, and the instances members should be hooked into the UI.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +    def set_binwarp(self, binwarp):
Convert all your setters and getters to be `@property` so the code is more Pythonic.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +            return None
Invert the condition and make this a guard clause.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +        return result
A `return` already implies that you're returning a result. You can just return this value outright.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +    GUI = True
What is the justification for this class variable?

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +        timer_period = 0.01  # seconds
Why isn't this an adjustable parameter for the class?

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +            self._publishers = {label: self.create_publisher(Image, "/" + label, 10) for label in image_labels}
The ROS integration should create an instance of the `LaneFollower` class and have it's inputs and outputs tied to the appropriate publisher and subscriber code so that it can be free standing without ROS.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +        self._publishers[label].publish(self._bridge.cv2_to_imgmsg(img_raw,encoding="bgr8"))
See like a function like this should just return `self._bridge.cv2_to_imgmsg(img_raw,encoding="bgr8")`

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +        return veh_pos / 100
What do these magic numbers mean? The parenthesis are unnecessary around the condition.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +        success_r, image_r = vidcap_right.read()
Confusing to follow since these are both global variables.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +                frame, matrix, (640, 480))
Again, magic numbers, make these constants so that anyone can read and understand!

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +                self._right_follower.set_binwarp(binwarp=mask)
A better way of organizing this is to have `self.followers` be an array with some kind of enum to index the right one, or a dictionary where you use `left` or `right` to index into the correct follower as opposed to assuming digits and names here and there.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +                self.camData_publisher.publish(msg_out)
Why are we setting the output data to be `1000.0` here?

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +            return
Again, don't know the significance of any of these values.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +        self.show_plot = SHOW_PLOT
Why are we inconsistent about case here?

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +        imgs = [cv2.imread(img_loc) for img_loc in img_locs]
This comment reiterates what the function is named.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +        if self.show_plot:
Invert the condition for a guard clause.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +    return binary_output
Isn't `(grad>thresh[0])&(grad<thresh[1])` already going to be a binary output? Just cast it to the correct type if that's what you want.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +        global fit_sum_right
These global variables could be avoided if you created a stand-alone plotter which takes and instance of the class and the parameters.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/LaneDetection.py
> +    rclpy.shutdown()
These comments restate the code but in a less concise way. Comments should explain why, not how since the code already does that.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +        sobel= cv2.Sobel(gray, cv2.CV_64F, 0,1)
It is confusing to call the variable `gray` when it might not always be gray. Just keep the `img` variable and if it's color or grayscale, it's still an image.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +def draw_lane(original_img, Combined_img, left_fitx, right_fitx, M):
`Combined_img` does not follow PEP 8 naming conventions.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +    xm_per_pix=3.7/700
Another magic number.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +    return direction
```suggestion
def get_direction(center_distance):
    return if 'right' if center_distance > 0 else 'left'
```

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/SobelVidCam.py
> +    cap = cv2.VideoCapture("/dev/video2")
Please use `argparse` to have this, along with all hard-coded paths to be parameters that are passed at runtime.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/VidCam.py
> +    return l, u, v
`cv2.split()`

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/VidCam.py
> +            # cv2.imshow("PLYFIT",out_img)
There shouldn't be commented out code, we use `git` for this very reason.

2024-05-19 01:49 UTC, jacobkoziej commented on ros2/src/lanefollowingtest/cam_publisher.py
> +        super().__init__('webcam_image_publisher')
The argument should be `WebcamImagePublisher`

2024-05-22 16:34 UTC, Vaibhav-Hariani commented
Realized I closed the wrong P.R, closing this one instead.

2024-05-22 16:34 UTC, closed without merging