User/ajaku/CAN naming consistency
CooperUnion/selfdrive pull request #79
Opened 2022-10-27 13:36 UTC by ajaku

CAN messages and signals have been renamed to improve consistency.

2022-10-27 13:46 UTC, jacobkoziej requested changes
Just a few changes to be made, @dmezh would you mind checking on the suggested bootloader renames?

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +- DBW_NodeStatus:
`NodeStatus`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +      - systemStatus:
`sysStatus`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +- DBW_NodeInfo:
`NodeInfo`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +- DBW_NodeSteeringCmd:
`WHL_SteeringCmd`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +      - source:
`src`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +- DBW_UpdaterUpdateData:
`UpdateData`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +- DBW_NodeUpdateResponse:
`UpdateResponse`

2022-10-27 13:46 UTC, jacobkoziej commented on can/can.yml
> +- DBW_UpdaterUpdateDone:
`UpdateDone`

2022-10-27 21:47 UTC, ajaku commented
All the reviews were implemented except for the Updater ones (still not sure what the deal is with those).

2022-10-27 23:42 UTC, dmezh commented
@ajaku you can leave the updater messages as-is. Looks like you have a merge conflict in can.yml.

2022-10-28 17:07 UTC, dmezh commented
@ajaku Ok, the updater message mess is mine to clean up.. can I push to your branch?

2022-11-04 19:25 UTC, jacobkoziej submitted a review, later dismissed

2022-11-04 21:26 UTC, dmezh commented on can/can.yml
> +           description: Githash of the currently-running firmware.
Extra spaces?

2022-11-04 21:28 UTC, dmezh commented on can/can.yml
> +- DBW_NodeUpdateResponse:
```suggestion
- NodeUpdateResponse:
```

It's ok, leave it for now. Will be reworked in bootloader PR

2022-11-04 21:31 UTC, dmezh submitted a review, later dismissed
Approving under the condition that this PR is merged squashed.

2022-11-04 21:39 UTC, jacobkoziej commented on can/can.yml
> +           description: Githash of the currently-running firmware.
Fixed. Ran the file through `yamllint`.

2022-11-04 21:40 UTC, jacobkoziej approved these changes

2022-11-04 21:46 UTC, dmezh commented
I didn't know you could approve PRs with your own commits in them 😶

2022-11-04 21:46 UTC, dmezh approved these changes

2022-11-04 21:51 UTC, merged